# This is an example file.

# When using the `url` parameter the `template` section of `.borg.toml`,
# the following configuration values should be added to 
# `.borg.template.toml` at the remote template URL, rather than `.borg.toml`.
[template]
files = [
    ".gitattributes",
    ".github/workflows/deploy.yml",
    ".gitignore",
    "CODE_OF_CONDUCT.md",
    "Makefile",
    "SECURITY.md",
    "mypy.ini",
    "pyproject.toml",
    "soar_template",
    "tests/test_python_version.py",
]
