[source]
# url = 'https://raw.githubusercontent.com/techservicesillinois/secdev-template-repository/refs/heads/main/'

# For testing: 
url = 'https://raw.githubusercontent.com/techservicesillinois/secdev-template-repository/refs/heads/feature/sync/'

# TODO: Switch to the `main` repo_url above when #22 is merged.
# https://github.com/techservicesillinois/secdev-template-repository/pull/22

[override_template]
# TODO: This is not implemented. This should be implemented or removed from this config.
files = [
    ".github/workflows/deploy.yml",
    "Makefile",
]
